### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by KatieMFritz** [KatieMFritz/codelab-js-objects#3]
Hey @chrisvfritz, can you take a look at this? It's [hosted here](http://soggy-cobweb.surge.sh/) and meets the following [project](http://lansingcodelab.com/lessons/js-objects/1) criteria:
- [x] Instead of storing each todo as a string, todos are stored as objects with `title`, `description`, and `isComplete` properties
- [x] The new todo input is upgraded to a `form` that collects both a title and a longer description
- [x] Each todo is displayed as a `checkbox`, which will be checked if `isComplete` is `true`
- [x] Each todo checkbox has a `label`, which contains the `title` of the todo
- [x] The `description` of each todo is stored in the `title` attribute of the `label`, so that it appears in a tooltip when users hold their mouse over the todo
- [x] For each todo, `isComplete` begins as `false`
- [x] Checking or unchecking a checkbox marks its `isComplete` attribute to `true` or `false`, respectively
- [x] Next to the "Clear All" button, an additional button exists to "Clear Completed"

**Comment by chrisvfritz** [comment]
This looks great! :smiley: :balloon: :shipit: Nothing needs to be changed here, but I do have a couple tips for the future:

### More consistent render function names

To make it more clear what your render functions are doing, I would prefix all of them with `render`. So instead of:

``` js
function renderAll() {
  renderTodos()
  countTodos()
  pickForMe()
}
```

I might use:

``` js
function renderAll() {
  renderTodos()
  renderTodosCount()
  renderPickForMeInstructionsOrButton()
}
```

That makes it much more clear to me (and others reading my code later) what each function is actually doing.

### Multi-property objects on several lines

When I have objects with several properties, I usually like to spread the properties out over multiple lines. So instead of:

``` js
todos.push({ title: newTodoTitle.value, description: newTodoDescription.value, isComplete: false })
```

I might write:

``` js
todos.push({
  title: newTodoTitle.value, 
  description: newTodoDescription.value, 
  isComplete: false 
})
```

### Simplest way to empty an array

While this technically does the job:

``` js
todos.splice(0)
```

There's an even simpler way to empty an array:

``` js
todos = []
```
